name: Android Debug

on:
  push:
    branches:
      - master

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      
      - name: Add environment variables to local.properties
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> local.properties
          echo "ML_URL=${{ secrets.ML_URL }}" >> local.properties
          echo "MAP_KEY=${{ secrets.MAP_KEY }}" >> local.properties
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: wander.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: v1.0.0  
          release_name: Release v1.0.0
          body: |
            Changes in this Release
            - First release of the app
          draft: false
          prerelease: false

      - name: Upload Release APK to GitHub Release
        id: upload-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCSESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
